<a href="https://colab.research.google.com/github/PrinceRaj1161/Numpy/blob/main/Numpy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# View and Copy of an array

In [19]:
# View and copy are used to copy numpy array

import numpy as np

x = np.array([1,2,4,5,7])
y = x.copy()

x[0]=89

print(x)
print(y)

# Changes won't be shown

[89  2  4  5  7]
[1 2 4 5 7]


In [20]:
import numpy as np

x = np.array([1,2,3,4,6])
y=x.view()

x[0]=37

print(x)
print(y)

# Changes would be shown

[37  2  3  4  6]
[37  2  3  4  6]
