<a href="https://colab.research.google.com/github/PrinceRaj1161/Numpy/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Slicing of the Array

In [1]:
# Calling numpy for all cases
import numpy as np

In [2]:
# Slicing through 1-D array

x = np.array([1,2,3,4,5,6])

# There are two ways for slicing.
# With steps
# Without steps

#Without steps

print(x[1:5])

#Negative indexing
print(x[-3:-1])

# With steps
print(x[::2])

[2 3 4 5]
[4 5]
[1 3 5]


In [3]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(x[::2])
print(x[3:8:2])

[ 1  3  5  7  9 11 13 15]
[4 6 8]


In [7]:
# Slicing in 2-D array
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(x)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [9]:
# Suppose we want to print

#  6  7  8
# 10 11 12
# 14 15 16

# First we take rows and then we go to columns

print(x[1:4,1:4])

[[ 6  7  8]
 [10 11 12]
 [14 15 16]]
