<a href="https://colab.research.google.com/github/PrinceRaj1161/Numpy/blob/main/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Datatypes

In [10]:
# Data types in numpy

# i for integer
# b for boolean
# u for unsigned integer
# f for float
# c for complex float
# m for timedelta
# M for datetime
# O for object
# S for string
# U for Unicode string
# V - memory


# Topics
# Use of dtype
# Creating array with defined datatype
# Create dtype of i4
# Use of astype()

In [11]:
# Use of dtypes

import numpy as np
x = np.array([1,2,3,4,5])
print(x,x.dtype)

x = np.array([1.2,1.3,1.2])
print(x,x.dtype)

x = np.array([True,False,True])
print(x,x.dtype)

x = np.array(["One","Two","Three"])
print(x,x.dtype)

[1 2 3 4 5] int64
[1.2 1.3 1.2] float64
[ True False  True] bool
['One' 'Two' 'Three'] <U5


In [17]:
# Creating array with defined datatypes

import numpy as np
x = np.array([1.2,2.3,6.7],dtype='i')
print(x,x.dtype)

x = np.array([6,7,0,0,1],dtype=bool)
print(x,x.dtype)

[1 2 6] int32
[ True  True False False  True] bool


In [18]:
# Use of astype

import numpy as np
x = np.array([1.23,1.73,8.27,91.272])
x = x.astype("i4")
print(x,x.dtype)



[ 1  1  8 91] int32
