<a href="https://colab.research.google.com/github/PrinceRaj1161/Numpy/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy

#To know the version we would use __version__

import numpy as np
print(np.__version__)

1.25.2


# Creating Arrays using numpy

In [1]:
import numpy as np
print(np.__version__)

1.25.2


In [2]:
# Create 1D array
x = np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# We can also pass a list,tuple, or any array like object with array()
import numpy as np
list1 = [1,2,3,4,5,6]
tuple1 = (1,2,3,4,5)

x1 = np.array(list1)
x2 = np.array(tuple1)

print(x1,type(x1))
print(x2,type(x2))

[1 2 3 4 5 6] <class 'numpy.ndarray'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [7]:
# Dimensions in Arrays - a dimension in arrays is one level of
# array is one level of array depth(nested array)

# 0-D Arrays - scalers are the elements in an array, each value in an array is a 0D

#Example of 0-D array
import numpy as np
x = np.array(42)
print(x,type(x))

42 <class 'numpy.ndarray'>


In [8]:
# 1-D Arrays - an array that has 0-D arrays as it's element is called uni-directional or 1-D

import numpy as np
x = np.array([1,2,3,4,5])
print(x,type(x))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [10]:
# 2-D arrays - an array that has 1-D arrays as it's element is called 2-D arrays.

import numpy as np
x = np.array([[1,2,4],[5,6,7]])
print(x,type(x))

[[1 2 4]
 [5 6 7]] <class 'numpy.ndarray'>


In [11]:
# 3-D arrays - an array that has 2-D arrays as it's element is called 3-D arrays

import numpy as np
x = np.array([[[1,2,3],[3,4,5]],[[6,7,8],[10,11,23]]])
print(x,type(x))

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [10 11 23]]] <class 'numpy.ndarray'>


In [14]:
# ndim :- It is used to know dimension of the array

import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,4],[5,6,7]])
d = np.array([[[1,2,3],[3,4,5]],[[6,7,8],[10,11,23]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
# Creating 5-D array using ndmin

import numpy as np
a = [1,2,3,4,5]
a = np.array(a,ndmin=5)
print(a)
print(a.ndim)

[[[[[1 2 3 4 5]]]]]
5
