<a href="https://colab.research.google.com/github/PrinceRaj1161/Numpy/blob/main/Shape6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Shape of an array

In [21]:
# In order to know the shape the array we use
import numpy as np

x = np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(x.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [24]:
import numpy as np
x = np.array([1,2,3,4,5],ndmin=5)
print(x)
print(x.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)
